name: Automation Test Run

on: 
  [workflow_dispatch]

jobs:
  newman:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: matt-ball/newman-action@master
        with:
          collection: src/Tests/postman_collection.json
          environment: src/Tests/postman_environment.json
          delayRequest: 100
