name: Automation Test Run

on: 
  [workflow_dispatch]

jobs:
  newman:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Test secret reading
        run: echo 'The secret is ${{ secrets.TEST_KEY }}'
